name: computational-biology-2025  
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python and system libraries
  - python=3.11
  - pip
  - setuptools
  - wheel
  
  # Scientific computing core
  - numpy>=1.26
  - scipy>=1.12
  - pandas>=2.2
  - matplotlib>=3.8
  - seaborn>=0.13
  - plotly>=5.17
  
  # Machine learning
  - scikit-learn>=1.4
  - pytorch>=2.1
  - torchvision
  - torchaudio
  - xgboost>=2.0
  
  # Bioinformatics specific
  - biopython>=1.83
  - pysam>=0.22
  - bedtools>=2.31
  - samtools>=1.19
  - bcftools>=1.19
  - htslib>=1.19
  
  # Data analysis and visualization
  - jupyter
  - jupyterlab>=4.0
  - notebook>=7.0
  - ipykernel
  - ipywidgets
  - bokeh>=3.3
  - altair>=5.2
  - networkx>=3.2
  
  # Statistical analysis
  - statsmodels>=0.14
  
  # Image processing and computer vision
  - opencv>=4.9
  - pillow>=10.2
  - scikit-image>=0.22
  - imageio>=2.33
  
  # Parallel computing
  - dask>=2024.1
  - joblib>=1.3
  - numba>=0.59
  - pathos>=0.3
  
  # Database and I/O
  - h5py>=3.10
  - pytables>=3.9
  - sqlalchemy>=2.0
  - openpyxl>=3.1
  
  # Web scraping and APIs
  - requests>=2.31
  - beautifulsoup4>=4.12
  - aiohttp>=3.9
  
  # Development tools
  - pytest>=8.0
  - black>=24.0
  - flake8>=7.0
  - tqdm>=4.66
  
  # Additional computational biology tools
  - pybedtools>=0.9
  - intervaltree>=3.1
  
  # Pip packages for specialized tools
  - pip:
      - scanpy>=1.9.6
      - anndata>=0.10.5
      - scvi-tools>=1.0.4
      - harmonypy>=0.0.9
      - scrublet>=0.2.3
      - pyscenic>=0.12.1
      - episcanpy>=0.4.0
      - mudata>=0.2.3
      - squidpy>=1.3.0
      - blosc2>=2.7.1
      - msgpack>=1.0.8
      - tables>=3.10.1
